baseURL = 'https://jakubsp.github.io/'
languageCode = 'cs'
defaultContentLanguage = 'cs'
title = 'Jakub | Pentesting & Security'
theme = 'blowfish'

[params]
    nickname = "Jakub"
    description = "Portfolio zaměřené na pentesting a Offensive Security path na TryHackMe."
    author = "Jakub"

[menu]
  [[menu.main]]
    name = "O mně"
    url = "/about/"
    weight = 10
